### ISSUE TITLE
Error: must provide pattern

### ISSUE THREAD

**Issue by semsphy** [ruysu/laravel-elixir-bower-files#1]
``` bash
Starting 'bowerJs'...
[15:52:18] 'bowerJs' errored after 147 ms
[15:52:18] Error: must provide pattern
    at new GlobSync (/mnt/center/projects/hotel/modules/Core/Resources/themes/default/node_modules/glob/sync.js:29:11)
    at Function.globSync [as sync] (/mnt/center/projects/hotel/modules/Core/Resources/themes/default/node_modules/glob/sync.js:24:10)
    at /mnt/center/projects/hotel/modules/Core/Resources/themes/default/node_modules/globby/index.js:86:26
    at Array.reduce (native)
    at Function.module.exports.sync (/mnt/center/projects/hotel/modules/Core/Resources/themes/default/node_modules/globby/index.js:85:34)
    at mainFiles (/mnt/center/projects/hotel/modules/Core/Resources/themes/default/node_modules/bower-files/lib/utils/main-files.js:8:17)
    at new MainComponent (/mnt/center/projects/hotel/modules/Core/Resources/themes/default/node_modules/bower-files/lib/main-component.js:31:16)
    at new BowerFiles (/mnt/center/projects/hotel/modules/Core/Resources/themes/default/node_modules/bower-files/lib/bower-files.js:25:21)
    at BowerFiles (/mnt/center/projects/hotel/modules/Core/Resources/themes/default/node_modules/bower-files/lib/bower-files.js:19:47)
    at null.definition (/mnt/center/projects/hotel/modules/Core/Resources/themes/default/node_modules/laravel-elixir-bower-files/index.js:34:54)
[15:52:18] Error in plugin 'run-sequence'
Message:
    An error occured in task 'bowerJs'.
```

**Comment by ruysu** [comment]
I believe it is a compatibility issue with the glob module used by bowerfiles, I'm already looking into it

**Comment by FDiskas** [comment]
Got same problem

**Comment by veneliniliev** [comment]
and i!

**Comment by underfloorheat** [comment]
Moi aussi
